#!/bin/bash

##
# ____ _ ___    ____ ____ ____ _    _  _
# | __ |  |  __ |__/ |___ |__| |    |\/|
# |__] |  |     |  \ |___ |  | |___ |  |
#
VER="2.0.0"
# by dehahost (https://github.com/dehahost)
##

## Config

# - Separator between prefix and realm name
#   Default is "-"
SEPARATOR="-"
# - Common branch name
#   Could be "main", default is "master"
COMMON_BRANCH="master"
# - Where should be saved output of cracklib-unpacker
#   openSUSE only, default is "/tmp/cracklib_pw.dict"
UNPACK_PATH="/tmp/cracklib_pw.dict"


## Functions

# - Load realm.* key-vals from git config
load_from_git_config() {
    local kv=( $(git config -l | grep -E '^realm\..+$') )
    for v in "${kv[@]}"; do
        local _k=$(echo ${v} | sed -E 's/realm\.(\w+)=.+/\1/')
        local _v=$(echo ${v} | sed -E 's/realm\.\w+=(.+)/\1/')
        set_conf ${_k} ${_v}
    done
}

# - Set configuration
set_conf() {
    case ${1} in
        "separator")     SEPARATOR=${2};;
        "common-branch") COMMON_BRANCH=${2};;
    esac
}

# - Realm name formatter
realm_name() {
    [[ ${1} =~ ^${REALM_PREFIX} ]] && echo ${1#*${SEPARATOR}} || echo ${1}
}

# - Realm branch name formatter
realm_branch() {
    [[ ${1} =~ ^${REALM_PREFIX} ]] && echo ${1} || echo ${REALM_PREFIX}${1}
}

# - Realm branch matcher
realm_exists() {
    local input=$(realm_branch ${1})
    for _r in ${REALM_BRANCHES[@]}; do
        [[ ${input} == ${_r} ]] && unset _r && return 0
    done
    unset _r && return 1
}

# - Dictionary path
#
opensuse_unpack_cracklib() {
    [[ -r ${UNPACK_PATH} ]] && return
    echo "Unpacking cracklib password dict to ${UNPACK_PATH}..."
    ${SUDO} cracklib-unpacker /usr/share/cracklib/pw_dict >${UNPACK_PATH}
}

decide_dictionary() {
    case $1 in
        "openSUSE")
            opensuse_unpack_cracklib
            DICT_PATH="${UNPACK_PATH}"
     ;; *)
            DICT_PATH="/usr/share/dict/cracklib-small"
     ;;
    esac
}


## Statup procedures
[[ ${USER} != "root" ]] && SUDO="sudo"
OS_NAME=$(cat /etc/*-release | grep ^NAME | cut -d\" -f2 | cut -d" " -f1)

decide_dictionary ${OS_NAME}
load_from_git_config


## Constants
CURRENT_BRANCH=$(git branch 2>/dev/null | sed -e '/^[^*]/d; s/\* \(.*\)/\1/')

REALM_PREFIX="realm${SEPARATOR}"
REALM_GENERATED_NAME="${REALM_PREFIX}$(echo -n $(shuf -n2 ${DICT_PATH}) | sed -E "s/['\.&+\\-]//g; s/\s/-/g")"
REALM_BRANCHES=( $(git branch 2>/dev/null | grep -oE "${REALM_PREFIX}[^ ]+") )


## Program section
# - Are we in a Git repo?
if [[ ${CURRENT_BRANCH} == "" && ${1} != "help" ]]; then
    echo "You are not in a Git repository."
    exit 1
fi

case ${1} in
    "enter")
        realm=${REALM_GENERATED_NAME}
        tail=""

        # - Enter a new realm or a existing one
        if [[ ${2} == "-c" && ${CURRENT_BRANCH} != ${COMMON_BRANCH} ]]; then
            echo "Going to checkout from ${COMMON_BRANCH} branch."
            tail=${COMMON_BRANCH}
            shift
        fi

        # Match and use user typed realm name or use randomly generated one
        # This allows user to choose custom two worlded realm name
        if [[ ${2} =~ ^(${REALM_PREFIX})?[a-zA-Z0-9]+-[a-zA-Z0-9]+$ ]]; then
            realm=$(realm_branch ${2})
        fi

        # Skip if alredy in wanted realm
        if [[ ${realm} == ${CURRENT_BRANCH} ]]; then
            echo "Already in realm '$(realm_name ${realm})'"
            exit
        fi

        # Checkout existing realm branch or a new one
        if realm_exists ${realm}; then
            echo "Entering realm called '$(realm_name ${realm})'..."
            git checkout ${realm} ${tail}
            exit
        fi

        echo "Creating a new realm called '$(realm_name ${realm})'..."
        git checkout -b ${realm} ${tail}

 ;; "leave")
        # Only leave realm branch when user is currenly in it.
        if [[ ! ${CURRENT_BRANCH} =~ ^${REALM_PREFIX}.*$ ]]; then
            echo "You are not in the realm."
            exit 1
        fi

        echo "Leaving realm called '$(realm_name ${CURRENT_BRANCH})'..."
        git checkout ${COMMON_BRANCH}

 ;; "dispose")
        # - Delete the realm without any traces

        # Support disposing realm by inputed name
        if [[ ${2} != "" && ${2} != ${CURRENT_BRANCH} ]]; then
            if ! realm_exists ${2}; then
                echo "Entered realm '$(realm_name ${2})' do not exist!"
                exit 1
            fi

            echo "Disposing realm called '$(realm_name ${2})'..."
            git branch -D $(realm_branch ${2})
            exit
        fi

        if [[ ! ${CURRENT_BRANCH} =~ ^${REALM_PREFIX}.*$ ]]; then
            echo "You are not in the realm."
            exit 1
        fi

        echo "Leaving and disposing currently used realm called '$(realm_name ${CURRENT_BRANCH})'..."
        git checkout -f ${COMMON_BRANCH}
        git branch -D ${CURRENT_BRANCH}

 ;; "reword")
        # - Rename current realm

        if [[ ! ${CURRENT_BRANCH} =~ ^${REALM_PREFIX}.*$ ]]; then
            echo "You are not in the realm."
            exit 1
        fi

        realm=${REALM_GENERATED_NAME}

        # Allow user to enter new realm name
        if [[ ${2} =~ ^(${REALM_PREFIX})?[a-zA-Z0-9]+-[a-zA-Z0-9]+$ ]]; then
            realm=$(realm_branch ${2})
        fi

        # Check - existing branch
        if realm_exists ${realm}; then
            echo "Cannot reword to '$(realm_name ${realm})' because it is already taken!"
            exit 1
        fi

        echo "Rewording to '$(realm_name ${realm})'..."
        git branch -M ${CURRENT_BRANCH} ${realm}

 ;; "list")
        # - List realm branches
        echo "${REALM_BRANCHES[@]}" | sed -e "s/ /\n/g; s/${REALM_PREFIX%${SEPARATOR}*}\\${SEPARATOR}//g"

 ;; "help")
        # - Man-like help
        cat <<EOF
git-realm
version ${VER}; by dehahost (https://github.com/dehahost)

SYNOPSIS
    git-realm enter [-c] [realm-name]
    git-realm reword [new-realm-name]
    git-realm leave
    git-realm dispose [realm-name]
    git-realm list

DESCRIPTION
    git-realm takes a different approach to branch naming.
    It offers efficient way to work with git branches and getting things done quickly.

COMMANDS
    dispose [realm-name]
        Disposes current or given realm name and returns back to ${COMMON_BRANCH} branch.

    enter
        Creates or checks out existing realm branch.

        [-c]
            When used, new realm is created from ${COMMON_BRANCH} branch.
            Argument have to be typed after the 'enter' command.

        [realm-name]
            Allows to enter existing realms or create new ones with a custom name.
            See the NAMING CONVENTIONS section to learn more.

    leave
        Returns back to ${COMMON_BRANCH} branch.

    list
        Lists all known realms in the Git repository.

    reword
        Rewords currently used realm to a randomly choosen or given name.

        [new-realm-name]
            Allows to enter desired realm name.
            See the NAMING CONVENTIONS section to learn more.

NAMING CONVENTIONS
    Realm name
        Realm name MUST consists from a prefix - word 'realm' - and two words.
        Those three words MUST be separated by '${SEPARATOR}'. First separator MAY BE a dash or a slash.
        Two words after a prefix CAN be manually entered by a user or anoter script or program. Two random words will be used by default.

        This can be converted into a simple regular expression:
            ^(${REALM_PREFIX})?[a-zA-Z0-9]+-[a-zA-Z0-9]+$

EOF

 ;; *)
        echo "Wrong command. Type 'git realm help' for help."
esac
